import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MetaMaskContextProvider } from "@/context/useMetaMask";
import { TimeProvider } from "@/context/TimerContext";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MetaMaskContextProvider>
          <TimeProvider>
            {children}
            <Footer />
          </TimeProvider>
        </MetaMaskContextProvider>
      </body>
    </html>
  );
}